import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { LayoutProps as Props } from "./types";
import Providers from "@/components/globals/Providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const RootLayout = async (props: Props) => {
  const { children } = props;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
